---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharded-cache-operator-manager-role
rules:
- apiGroups:
  - cache.operators.io
  resources:
  - shardedcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.operators.io
  resources:
  - shardedcaches/finalizers
  verbs:
  - update
- apiGroups:
  - cache.operators.io
  resources:
  - shardedcaches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
